function Kr = g_errorflield_Kr(in1)
%G_ERRORFLIELD_KR
%    KR = G_ERRORFLIELD_KR(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    20-Jan-2020 13:35:24

r1 = in1(1,:);
r2 = in1(2,:);
t2 = r1.^2;
t3 = r2.^2;
t4 = t2+t3;
t5 = 1.0./t4.^(3.0./2.0);
t6 = t4.^(3.0./2.0);
Kr = reshape([t5.*(t3-t6),-r1.*r2.*t5,-r1.*r2.*t5,t5.*(t2-t6)],[2,2]);
