function f = ML_get_sum_node_forces(r, ro, k)

f4 = get_force_exact(r(:,4), r(:,5), k(4), ro(4)) +...
     get_force_exact(r(:,4), r(:,6), k(6), ro(6)) +...
     get_force_exact(r(:,4), r(:,1), k(7), ro(7)) +...
     get_force_exact(r(:,4), r(:,2), k(11), ro(11));

f5 = get_force_exact(r(:,5), r(:,4), k(4), ro(4)) +...
     get_force_exact(r(:,5), r(:,6), k(5), ro(5)) +...
     get_force_exact(r(:,5), r(:,2), k(8), ro(8)) +...
     get_force_exact(r(:,5), r(:,3), k(12), ro(12));

f6 = get_force_exact(r(:,6), r(:,5), k(5), ro(5)) +...
     get_force_exact(r(:,6), r(:,4), k(6), ro(6)) +...
     get_force_exact(r(:,6), r(:,3), k(9), ro(9)) +...
     get_force_exact(r(:,6), r(:,1), k(10), ro(10));

f = [f4 f5 f6];
end

